def print_menu():
    menu = "\nOptions:\n"
    menu += "   0. Load the file\n"
    # menu += "   -1. Save to file\n"
    # menu += "   1. The number of vertices\n"
    # menu += "   2. Print all vertices\n"
    # menu += "   3. Given two vertices, find out whether there is an edge from the first one to the second one\n"
    # menu += "   4. Degrees\n"
    # menu += "   5. Modify the cost of an edge\n"
    # menu += "   6. Print isolated vertices\n"
    # menu += "   7. Add edge\n"
    # menu += "   8. Remove edge\n"
    # menu += "   9. Add vertex\n"
    # menu += "   10. Remove vertex\n"
    # menu += "   11. Print graph\n"
    # menu += "   12. Make a copy of the graph\n"
    # menu += "   13. Print the copy of the graph\n"
    # menu += "   14. Parse the set of inbound edges of a specified vertex\n"
    # menu += "   15. parse the set of outbound edges of a specified vertex\n"
    # menu += "   16. Generate a random graph having 7 vertices and 20 edges\n"
    # menu += "   17. Generate a random graph having 6 vertices and 40 edges\n"
    # menu += "   18. Generate random graph\n"
    # menu += "   19. Find the lowest length path between 2 vertices\n"
    # menu += "   20. Find the lowest cost walk between 2 vertices\n"
    # menu += "   21. Topological Sorting (DFS) + highest cost path in a DAG\n"
    menu += "   22. minimum cost Hamiltonian cycle\n"
    menu += "   exit. Exit the program\n"
    print(menu)
